crimemap/lib/crimemap_web/router.ex
defmodule CrimemapWeb.Router do
  use CrimemapWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CrimemapWeb do
    pipe_through  [:browser, CrimemapWeb.Plugs.Guest]

    get "/", PageController, :show
    get "/crimes", CrimeController, :index
  
    resources "/register", UserController, only: [:create, :new]
    
    get "/login", SessionController, :new
    post "/login", SessionController, :create
  end

  scope "/", CrimemapWeb do
    pipe_through [:browser, CrimemapWeb.Plugs.Auth]
    
    delete "/logout", SessionController, :delete

    get "/crime", CrimeController, :new
    post "/crime", CrimeController, :create
    get "/crime/:id", CrimeController, :show
    get "/crime/edit/:id", CrimeController, :edit
    put "/crime/edit/:id", CrimeController, :update
    delete "/crime/:id", CrimeController, :delete

    get "/user", UserController, :show
  end

  # API
  scope "/api", CrimemapWeb do
    pipe_through :api

    resources "/crimes", API.CrimeController, only: [:index]
  end
end

crimemap/lib/crimemap_web/views/layout_view.ex
defmodule CrimemapWeb.LayoutView do
  use CrimemapWeb, :view
end

crimemap/lib/crimemap_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="shortcut icon" type="image/png" href="<%= Routes.static_path(@conn, "/images/favicon/favicon.ico") %>"/>

    <title>Crimemap · Map of crimes.</title>
    <script src="https://kit.fontawesome.com/a03b4c51b2.js"></script>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
    <nav class="navbar is-black" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="/">
            <img src="<%= Routes.static_path(@conn, "/images/logo/menu.png") %>" width="32" height="32">
          </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <%= link "My profile", to: Routes.user_path(@conn, :show), method: :get, class: "navbar-item" %>
            <%= link "Crimes", to: Routes.crime_path(@conn, :index), method: :get, class: "navbar-item" %>
          </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <%= if signed_in?(@conn) do %>
                  <%= link "Logout", to: Routes.session_path(@conn, :delete), method: :delete, class: "button is-light" %>
                <% else %>
                  <%= link "Sign up", to: Routes.user_path(@conn, :new), class: "button is-primary" %>
                  <%= link "Log in", to: Routes.session_path(@conn, :new), method: :get, class: "button is-light" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <%= render @view_module, @view_template, assigns %>

    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>